Modules/ResumeCV/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('templates/{id?}', 'ResumecvtemplateController@getAllTemplateThemes')->name('templates');

Route::get('publish/{slug}', 'ResumeCVController@publish')->name('resumecv.publish');
Route::post('get-page-json/{code}', 'ResumeCVController@getPageJson');


Route::middleware('auth')->group(function () {

	Route::middleware('can:candidate')->group(function () {

		Route::get('alltemplates/{id?}', 'ResumecvtemplateController@getAllTemplate')->name('alltemplates');
		Route::prefix('resumecv')->group(function() {
			Route::get('download/{item}', 'ResumeCVController@download')->name('resumecv.download');
		    Route::get('/', 'ResumeCVController@index')->name('resumecv.index');
		    Route::get('builder/{code}/{type?}', 'ResumeCVController@builder')->name('resumecv.builder');
			Route::post('save', 'ResumeCVController@save')->name('resumecv.save');
			// Load builder
			Route::post('update-builder/{id}', 'ResumeCVController@updateBuilder')->name('resumecv.updateBuilder');
			Route::get('load-builder/{id}', 'ResumeCVController@loadBuilder')->name('resumecv.loadBuilder');
			Route::post('clone/{item}', 'ResumeCVController@clone')->name('resumecv.clone');
			Route::delete('delete/{item}', 'ResumeCVController@delete')->name('resumecv.delete');

			Route::post('uploadimage', 'ResumeCVController@uploadImage');
	    	Route::post('deleteimage', 'ResumeCVController@deleteImage');
	    	Route::get('setting/{item}', 'ResumeCVController@setting')->name('resumecv.setting');
			Route::post('setting-update/{item}', 'ResumeCVController@settingUpdate')->name('resumecv.settings.update');
		});
		

    });

	// For admin and user
    Route::post('resumecvtemplate/loadtemplate/{id}', 'ResumecvtemplateController@loadTemplate')->name('loadtemplate');
	Route::post('resumecvtemplate/uploadimage', 'ResumecvtemplateController@uploadImage');
	Route::post('resumecvtemplate/deleteimage', 'ResumecvtemplateController@deleteImage');

	Route::middleware('can:admin')->prefix('settings')->name('settings.')->group(function () {
	
		Route::resource('resumecvtemplate', 'ResumecvtemplateController')->except('show');
		Route::resource('resumecvcategories', 'ResumecvcategoryController')->except('show');

		Route::post('resumecvtemplate/uploadimage', 'ResumecvtemplateController@uploadImage')->name('resumecvtemplate.uploadimage');
	    Route::post('resumecvtemplate/deleteimage', 'ResumecvtemplateController@deleteImage')->name('resumecvtemplate.deleteimage');

		Route::post('resumecvtemplate/clone/{id}', 'ResumecvtemplateController@clone')->name('resumecvtemplate.clone');
		// Builder template
		Route::get('resumecvtemplate/builder/{id}/{type?}', 'ResumecvtemplateController@builder')->name('resumecvtemplate.builder');
		
		// Load template builder
		Route::get('resumecvtemplate/load-builder/{id}', 'ResumecvtemplateController@loadBuilder')->name('resumecvtemplate.loadBuilder');

		Route::post('resumecvtemplate/update-builder/{id}', 'ResumecvtemplateController@updateBuilder')->name('resumecvtemplate.updateBuilder');


	});
});

Modules/ResumeCV/Entities/Resumecvcategory.php
<?php

namespace Modules\ResumeCV\Entities;

use Illuminate\Database\Eloquent\Model;

class Resumecvcategory extends Model
{
    protected $table = 'resumecvcategories';
    protected $dates = [
        'created_at',
        'updated_at',
    ];

    protected $fillable = [
        'name',
        'thumb',
        'color',
        'created_at',
        'updated_at',
    ];

    public function templates()
    {
        return $this->hasMany('Modules\ResumeCV\Entities\Resumecvtemplate','category_id');
    }
}

Modules/ResumeCV/Http/Controllers/ResumecvcategoryController.php
<?php
namespace Modules\ResumeCV\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\ResumeCV\Entities\Resumecvcategory;

class ResumecvcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index(Request $request)
    {
        $data = Resumecvcategory::query();

        if ($request->filled('search'))
        {
            $data->where('name', 'like', '%' . $request->search . '%');
        }

        $data = $data->paginate(10);

        return view('resumecv::resumecvcategories.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('resumecv::resumecvcategories.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate(['name' => 'required', ]);
        $form_data = array(
            'name' => $request->name,
        );

        $user = Resumecvcategory::create($form_data);

        return redirect()->route('settings.resumecvcategories.index')
            ->with('success', __('Created successfully'));

    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $category = Resumecvcategory::findorFail($id);
        return view('resumecv::resumecvcategories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(['name' => 'required']);

        $form_data = array(
            'name' => $request->name,
        );

        Resumecvcategory::whereId($id)->update($form_data);

        return redirect()->route('settings.resumecvcategories.index')
            ->with('success', __('Updated successfully'));
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        $item = Resumecvcategory::find($id);
        
        if ($item->templates()->count() > 0) {
            return redirect()->route('settings.resumecvcategories.index')->with('error',"Can't delete because it has template in it");
        }
        $delete_status = $item->delete();

        return redirect()->route('settings.resumecvcategories.index')->with('success','Deleted successfully');
    }
}

Modules/ResumeCV/Resources/views/resumecvcategories/create.blade.php
@extends('core::layouts.app')

@section('title', __('Categories'))

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@lang('Categories')</h1>
</div>
<div class="row">
    <div class="col-md-12">

        <form role="form" method="post" action="{{ route('settings.resumecvcategories.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <div class="form-group">
                                <label class="form-label">@lang('Name')</label>
                                <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="@lang('Name')">
                            </div>

                        </div>
                        
                    </div>

                </div>
                <div class="card-footer">
                    <div class="d-flex">
                        <a href="{{ route('settings.resumecvcategories.index') }}" class="btn btn-secondary">@lang('Cancel')</a>
                        <button class="btn btn-primary ml-auto">@lang('Save')</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
    
</div>


@stop

Modules/ResumeCV/Resources/views/resumecvcategories/edit.blade.php
@extends('core::layouts.app')

@section('title', __('Update Catetory'))

@section('content')


<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@lang('Update Catetory')</h1>
</div>
<div class="row">
    <div class="col-md-12">

        <form role="form" method="post" action="{{ route('settings.resumecvcategories.update', $category->id) }}" enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="form-label">@lang('Name')</label>
                                <input type="text" name="name" value="{{$category->name}}" class="form-control" placeholder="@lang('Name')">
                            </div>

                        </div>
                        
                    </div>

                </div>
                <div class="card-footer">
                    <div class="d-flex">
                        <a href="{{ route('settings.resumecvcategories.index') }}" class="btn btn-secondary">@lang('Cancel')</a>
                        <button class="btn btn-primary ml-auto">@lang('Save')</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
    
</div>
@stop

Modules/ResumeCV/Resources/views/resumecvcategories/index.blade.php
@extends('core::layouts.app')
@section('title', __('Categories'))
@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@lang('Categories')</h1>
    <a href="{{ route('settings.resumecvcategories.create') }}" class="btn btn-sm btn-success shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> @lang('Create Category')</a>
</div>

<div class="row">
    <div class="col-md-12">
        @if($data->count() > 0)
            <div class="card">
                <div class="table-responsive">
                    <table class="table card-table table-vcenter text-nowrap">
                        <thead class="thead-dark">
                            <tr>
                                <th>@lang('Name')</th>
                                <th>@lang('Date Created')</th>
                                <th>@lang('Date Modified')</th>
                                <th>@lang('Action')</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>

                                <td>

                                    <a href="{{ route('settings.resumecvcategories.edit', $item) }}">{{ $item->name }}</a>
                                </td>
                                
                               <td>
                                <div class="small text-muted">
                                        {{$item->created_at->format('M j, Y')}}
                                </div>
                                </td>
                                <td>
                                        <div class="small text-muted">
                                                {{$item->updated_at->format('M j, Y')}}
                                        </div>
                                </td>
                                
                                <td>
                                     <div class="d-flex">
                                        <div class="p-1 ">
                                             <a href="{{ route('settings.resumecvcategories.edit', $item) }}" class="btn btn-sm btn-primary">@lang('Edit')</a>
                                        </div>
                                        <div class="p-1 ">
                                                <form method="post" action="{{ route('settings.resumecvcategories.destroy', $item) }}" onsubmit="return confirm('@lang('Confirm delete?')');">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-sm btn-danger btn-clean">
                                                        @lang('Delete')
                                                    </button>
                                                </form>
                                        </div>
                                    </div>
                                   
                                    
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        @endif
        <div class="mt-4">
            {{ $data->appends( Request::all() )->links() }}
        </div>
        
        @if($data->count() == 0)
        <div class="alert alert-primary text-center">
            <i class="fe fe-alert-triangle mr-2"></i> @lang('No Categories found')
        </div>
        @endif
    </div>
    
</div>

@stop