Modules/Location/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('auth')->group(function () {
	Route::middleware('can:admin')->prefix('settings')->name('settings.')->group(function () {
		// attributes
		Route::group(['prefix' => 'location', 'as' => 'location.'], function(){

			// countries
			Route::group(['prefix' => 'countries', 'as' => 'countries.'], function(){
				Route::get('', 'CountriesController@index')->name('index');
				Route::get('create', 'CountriesController@create')->name('create');
				Route::post('', 'CountriesController@store')->name('store');
				Route::get('{id}/edit', 'CountriesController@edit')->name('edit');
				Route::put('{id}', 'CountriesController@update')->name('update');
				Route::delete('{id}', 'CountriesController@destroy')->name('destroy');
			});

			// country details
			Route::group(['prefix' => 'country_details', 'as' => 'country_details.'], function(){
				Route::get('', 'CountryDetailsController@index')->name('index');
				Route::get('{id}/edit', 'CountryDetailsController@edit')->name('edit');
				Route::put('{id}', 'CountryDetailsController@update')->name('update');
			});

			// states
			Route::group(['prefix' => 'states', 'as' => 'states.'], function(){
				Route::get('', 'StatesController@index')->name('index');
				Route::get('create', 'StatesController@create')->name('create');
				Route::post('', 'StatesController@store')->name('store');
				Route::get('{id}/edit', 'StatesController@edit')->name('edit');
				Route::put('{id}', 'StatesController@update')->name('update');
				Route::delete('{id}', 'StatesController@destroy')->name('destroy');
				Route::get('ajaxgetstates', 'StatesController@ajaxGetStates')->name('ajaxgetstates');
			});

			// cities
			Route::group(['prefix' => 'cities', 'as' => 'cities.'], function(){
				Route::get('', 'CitiesController@index')->name('index');
				Route::get('create', 'CitiesController@create')->name('create');
				Route::post('', 'CitiesController@store')->name('store');
				Route::get('{id}/edit', 'CitiesController@edit')->name('edit');
				Route::put('{id}', 'CitiesController@update')->name('update');
				Route::delete('{id}', 'CitiesController@destroy')->name('destroy');
				Route::get('ajaxgetcities', 'CitiesController@ajaxGetCities')->name('ajaxgetcities');
			});
			
		});
	});
});
		

Modules/Location/Entities/State.php
<?php

namespace Modules\Location\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Location\Entities\Country;
use Modules\Location\Entities\City;

class State extends Model
{
    protected $table = 'location_states';

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    protected $fillable = [
        'country_id',
        'name',
        'is_default',
        'is_active',
        'sort_order',
    ];
   
    protected $casts = [
        'is_default' => 'boolean',
        'is_active' => 'boolean',
    ];

    public function scopeDefault($query)
    {
        return $query->where('is_default', '=', 1);
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', '=', 1);
    }

    public function deleteChain()
    {
        $cities = $this->cities()->get();
        foreach ($cities as $city) {
            $city->deleteChain();
        }

        $this->delete();
    }

    public function country()
    {
        return $this->belongsTo(Country::class, 'country_id', 'id');
    }
    public function cities()
    {
        return $this->hasMany(City::class, 'state_id', 'id');
    }
}

Modules/Location/Http/Controllers/StatesController.php
<?php

namespace Modules\Location\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Location\Http\Requests\StateStoreRequest;
use Modules\Location\Http\Requests\StateUpdateRequest;
use Modules\Location\Entities\State;
use Modules\Location\Entities\Country;

class StatesController extends Controller
{
    public function index(Request $request)
    {
        $query = State::query()->with('country');

        if ($request->filled('search'))
        {
            $query->where('name', 'like', '%' . $request->input('search') . '%');
        }

        $paginationData = $query->paginate(10);

        return view('location::states.index', [
            'paginationData' => $paginationData,
        ]);
    }

    public function create(Request $request)
    {
        $countries = Country::get();
        return view('location::states.create', [
            'countries' => $countries,
        ]);
    }

    public function store(StateStoreRequest $request)
    {
        $data = $request->validated();
        Country::findOrFail($data['country_id']);

        $item = State::create($data);
        
        if($item->is_default) {
            State::where('id', '!=', $item->id)->update(['is_default' => false]);
        }

        return redirect()->route('settings.location.states.edit', ['id' => $item->id])->with('success', __('Created success !'));
    }

    public function edit(Request $request, $id)
    {
        $item = State::findOrfail($id);
        $countries = Country::get();

        return view('location::states.edit', [
            'item' => $item,
            'countries' => $countries,
        ]);
    }

    public function update(StateUpdateRequest $request, $id)
    {
        $item = State::findOrFail($id);
        $data = $request->validated();
        Country::findOrFail($data['country_id']);

        $item->update($data);

        if($item->is_default) {
            State::where('id', '!=', $item->id)->update(['is_default' => false]);
        }

        return redirect()->route('settings.location.states.edit', ['id' => $item->id])->with('success', __('Updated success !'));
    }

    public function destroy(Request $request, $id)
    {
        $item = State::findOrFail($id);
        $item->deleteChain();
        return redirect()->back()->with('success', __('Deleted success !'));
    }

    public function show(Request $request, $id)
    {
      abort(404);
    }

    public function ajaxGetStates(Request $request)
    {
        $result = [];
        $country_id = $request->input('country_id');
        if(isset($country_id)) {
            $result = State::where('country_id', '=', $country_id)->select('id', 'name')->get()->toArray();
        }
        return response()->json($result);
    }
}

Modules/Location/Resources/views/states/create.blade.php
@extends('core::layouts.app')

@section('title', __('Create State'))

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@lang('Create State')</h1>
</div>
<div class="row">
    <div class="col-md-12">

        <form role="form" method="post" action="{{ route('settings.location.states.store') }}">
            @csrf
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <div class="form-group">
                                <label class="form-label">@lang('Country')</label>
                                <select name="country_id" class="form-control">
                                    @foreach($countries as $country)
                                        <option value="{{ $country->id }}" {{ old('country_id') == $country->id ? 'selected' : '' }}>{{ $country->name }}</option>
                                    @endforeach
                                </select>
                                @error('country_id')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="form-label">@lang('State')</label>
                                <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="@lang('State')">
                                @error('name')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="form-label">@lang('Is default')</label>
                                <div>
                                    <label><input type="radio" name="is_default" value="1" {{ old('is_default', '1') == '1' ? 'checked' : '' }}> @lang('Yes')</label>
                                    &nbsp;&nbsp;&nbsp;&nbsp;
                                    <label><input type="radio" name="is_default" value="0" {{ old('is_default', '1') == '0' ? 'checked' : '' }}> @lang('No')</label>
                                </div>
                                @error('is_default')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="form-label">@lang('Is active')</label>
                                <div>
                                    <label><input type="radio" name="is_active" value="1" {{ old('is_active', '1') == '1' ? 'checked' : '' }}> @lang('Active')</label>
                                    &nbsp;&nbsp;&nbsp;&nbsp;
                                    <label><input type="radio" name="is_active" value="0" {{ old('is_active', '1') == '0' ? 'checked' : '' }}> @lang('In-active')</label>
                                </div>
                                @error('is_active')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                        </div>
                        
                    </div>

                </div>
                <div class="card-footer">
                    <div class="d-flex">
                        <a href="{{ route('settings.location.states.index') }}" class="btn btn-secondary">@lang('Cancel')</a>
                        <button class="btn btn-primary ml-auto">@lang('Save')</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
    
</div>


@stop

Modules/Location/Resources/views/states/edit.blade.php
@extends('core::layouts.app')

@section('title', __('Edit State'))

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@lang('Edit State')</h1>
</div>
<div class="row">
    <div class="col-md-12">

        <form role="form" method="post" action="{{ route('settings.location.states.update', ['id' => $item->id]) }}">
            @csrf
            @method('PUT')
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <div class="form-group">
                                <label class="form-label">@lang('Country')</label>
                                <select name="country_id" class="form-control">
                                    @foreach($countries as $country)
                                        <option value="{{ $country->id }}" {{ old('country_id', $item->country_id) == $country->id ? 'selected' : '' }}>{{ $country->name }}</option>
                                    @endforeach
                                </select>
                                @error('country_id')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="form-label">@lang('State')</label>
                                <input type="text" name="name" value="{{ old('name', $item->name) }}" class="form-control" placeholder="@lang('State')">
                                @error('name')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="form-label">@lang('Is default')</label>
                                <div>
                                    <label><input type="radio" name="is_default" value="1" {{ old('is_default', $item->is_default) == '1' ? 'checked' : '' }}> @lang('Yes')</label>
                                    &nbsp;&nbsp;&nbsp;&nbsp;
                                    <label><input type="radio" name="is_default" value="0" {{ old('is_default', $item->is_default) == '0' ? 'checked' : '' }}> @lang('No')</label>
                                </div>
                                @error('is_default')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="form-label">@lang('Is active')</label>
                                <div>
                                    <label><input type="radio" name="is_active" value="1" {{ old('is_active', $item->is_active) == '1' ? 'checked' : '' }}> @lang('Active')</label>
                                    &nbsp;&nbsp;&nbsp;&nbsp;
                                    <label><input type="radio" name="is_active" value="0" {{ old('is_active', $item->is_active) == '0' ? 'checked' : '' }}> @lang('In-active')</label>
                                </div>
                                @error('is_active')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>

                        </div>
                        
                    </div>

                </div>
                <div class="card-footer">
                    <div class="d-flex">
                        <a href="{{ route('settings.location.states.index') }}" class="btn btn-secondary">@lang('Cancel')</a>
                        <button class="btn btn-primary ml-auto">@lang('Save')</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
    
</div>


@stop

Modules/Location/Resources/views/states/index.blade.php
@extends('core::layouts.app')
@section('title', __('States'))
@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
      <div>
        <a href="{{ route('settings.location.states.create') }}" class="btn btn-primary">@lang('New State')</a>
      </div>
      <form method="get" action="" class="my-3 my-lg-0 navbar-search">
          <div class="input-group">
              <input type="text" name="search" value="{{ \Request::get('search', '') }}" class="form-control bg-light border-0 small" placeholder="@lang('Search')" aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                  <button class="btn btn-primary" type="submit">
                      <i class="fas fa-search fa-sm"></i>
                  </button>
              </div>
          </div>
      </form>
  </div>

<div class="row">
    <div class="col-md-12">
        @if($paginationData->count() > 0)
            <div class="card">
                <div class="table-responsive">
                    <table class="table card-table table-vcenter text-nowrap">
                        <thead class="thead-dark">
                            <tr>
                                <th>@lang('Country')</th>
                                <th>@lang('State')</th>
                                <th>@lang('Default')</th>
                                <th>@lang('Active')</th>
                                <th>@lang('Action')</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($paginationData as $item)
                            <tr>
                                <td>{{ $item->country->name }}</td>
                                <td>{{ $item->name }}</td>
                                <td>
                                    @if($item->is_default)
                                        <span class="small text-success"><i class="fas fa-check-circle text-success"></i></span>
                                    @else
                                        <span class="small text-dander"><i class="fas fa-times-circle"></i></span>
                                    @endif
                                </td>
                                <td>
                                    @if($item->is_active)
                                        <span class="small text-success"><i class="fas fa-check-circle text-success"></i></span>
                                    @else
                                        <span class="small text-dander"><i class="fas fa-times-circle"></i></span>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{ route('settings.location.states.edit', ['id' => $item->id]) }}" class="btn btn-primary">@lang('Edit')</a>
                                    <form class="d-inline-block form-delete" action="{{ route('settings.location.states.destroy', ['id' => $item->id]) }}" method="post" onsubmit="{{ 'return confirm(\''. __('Delete item ?') .'\')' }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-delete">@lang('Delete')</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        @endif
        <div class="mt-4">
            {{ $paginationData->appends( Request::all() )->links() }}
        </div>
        
        @if($paginationData->count() == 0)
        <div class="alert alert-primary text-center">
            <i class="fe fe-alert-triangle mr-2"></i> @lang('No results')
        </div>
        @endif
    </div>
    
</div>

@stop