Modules/PagesWebsite/Routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Page Home page
Route::get('page/{slug}', 'PagesWebsiteController@pageWebsite')->name('pagewebsite');

Route::middleware('auth')->group(function () {
	Route::middleware('can:admin')->prefix('settings')->name('settings.')->group(function () {
		Route::resource('pagewebsites', 'PagesWebsiteController')->except('show');
	});
});

Modules/PagesWebsite/Entities/PageWebsite.php
<?php
namespace Modules\PagesWebsite\Entities;

use Illuminate\Database\Eloquent\Model;

class PageWebsite extends Model
{

    protected $fillable = [
        'title',
        'description',
        'slug',
        'is_active',
    ];

    protected $casts = [
        'is_active' => 'boolean',
    ];

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }
}

Modules/PagesWebsite/Http/Controllers/PagesWebsiteController.php
<?php

namespace Modules\PagesWebsite\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\PagesWebsite\Entities\PageWebsite;
use Str;
class PagesWebsiteController extends Controller
{
    
    public function pageWebsite($slug, Request $request)
    {
        $page = PageWebsite::where('slug', $slug)->first();

        if ($page) {
            
            $skin = config('app.SITE_LANDING');
            $user = $request->user();

            return view('themes::' . $skin . '.page', compact(
                'page',
                'user'
            ));
        }
        abort(404);
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = PageWebsite::orderByDesc('id');
        $data = $data->paginate(10);
        return view('pageswebsite::pagewebsites.index', compact(
            'data'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('pageswebsite::pagewebsites.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->request->add([
            'slug' => Str::slug($request->slug),
        ]);

        $request->validate([
            'title'       => 'required|string|max:255',
            'description' => 'required|string',
            'slug'          => 'required|string|unique:page_websites',
        ]);

        $dataRequest = $request->all();

        if (!$request->filled('is_active')) {
            $dataRequest['is_active'] = false;
        } else {
            $dataRequest['is_active'] = true;
        }


        PageWebsite::create($dataRequest);

        return redirect()->route('settings.pagewebsites.index')
            ->with('success', __('Created successfully'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = PageWebsite::findorFail($id);
        return view('pageswebsite::pagewebsites.edit', compact(
            'item'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $page = PageWebsite::findorFail($id);

        $request->request->add([
            'slug' => Str::slug($request->slug),
        ]);

        $request->validate([
            'title'       => 'required|string|max:255',
            'description' => 'required|string',
            'slug'          => 'required|string|unique:page_websites,slug,' . $page->id,
        ]);

        
        if (!$request->filled('is_active')) {
            $request->request->add([
                'is_active' => false,
            ]);
        } else {
            $request->request->add([
                'is_active' => true,
            ]);
        }
        


        $page->update($request->all());

        return redirect()->route('settings.pagewebsites.edit', $page)
            ->with('success', __('Updated successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Page  $page
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $page = PageWebsite::findorFail($id);
        $page->delete();

        return redirect()->route('settings.pagewebsites.index')
            ->with('success', __('Deleted successfully'));
    }
}

Modules/PagesWebsite/Resources/views/pagewebsites/create.blade.php
@extends('core::layouts.app')

@section('title', __('Create Page websites'))

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@lang('Create Page websites')</h1>
</div>
<div class="row">
    <div class="col-md-12">
        <form role="form" method="post" action="{{ route('settings.pagewebsites.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <div class="form-group">
                                <label class="form-label">@lang('Title')</label>
                                <input type="text" name="title" value="{{ old('name') }}" class="form-control" placeholder="@lang('Title')">
                            </div>
                            <div class="form-group">
                                <div class="form-label">@lang('Active')</div>
                                <label class="custom-switch">
                                    <input type="checkbox" name="is_active" class="custom-switch-input">
                                    <span class="custom-switch-indicator"></span>
                                    <span class="custom-switch-description">@lang('Allow active')</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="form-label">@lang('Slug')</label>
                                <input type="text" name="slug" value="{{ old('slug') }}" class="form-control" placeholder="@lang('Slug')">
                            </div>
                            <div class="form-group">
                                <label class="form-label">@lang('Description')</label>
                                <textarea name="description" id="description_pages_website" rows="4" class="form-control">{{ old('description') }}</textarea>
                            </div>
                            
                        </div>
     
                    </div>

                </div>
                <div class="card-footer">
                    <div class="d-flex">
                        <a href="{{ route('settings.pagewebsites.index') }}" class="btn btn-secondary">@lang('Cancel')</a>
                        <button class="btn btn-primary ml-auto">@lang('Save')</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
    
</div>


@stop

Modules/PagesWebsite/Resources/views/pagewebsites/edit.blade.php
@extends('core::layouts.app')

@section('title', __('Update Page websites'))

@section('content')


<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@lang('Update Page websites')</h1>
</div>
<div class="row">
    <div class="col-md-12">

        <form role="form" method="post" action="{{ route('settings.pagewebsites.update', $item->id) }}" enctype="multipart/form-data">
            @csrf
            @method('PUT')

            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <div class="form-group">
                                <label class="form-label">@lang('Title')</label>
                                <input type="text" name="title" value="{{$item->title}}" class="form-control" placeholder="@lang('Title')">
                            </div>
                          
                            <div class="form-group">
                                <div class="form-label">@lang('Active')</div>
                                <label class="custom-switch">
                                    @if ($item->is_active)
                                        <input type="checkbox" name="is_active" value="1" class="custom-switch-input" checked>
                                    @else 
                                        <input type="checkbox" name="is_active" value="0" class="custom-switch-input" >
                                    @endif
                                    
                                    <span class="custom-switch-indicator"></span>
                                    <span class="custom-switch-description">@lang('Allow active page')</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <label class="form-label">@lang('Slug')</label>
                                <input type="text" name="slug" value="{{$item->slug}}" class="form-control" placeholder="@lang('Slug')">
                            </div>

                            <div class="form-group">
                                <label class="form-label">@lang('Description')</label>
                                <textarea name="description" id="description_pages_website" rows="4" class="form-control">{{$item->description}}</textarea>
                            </div>
                            
                        </div>
                        
                    </div>

                </div>
                <div class="card-footer">
                    <div class="d-flex">
                        <a href="{{ route('settings.pagewebsites.index') }}" class="btn btn-secondary">@lang('Cancel')</a>
                        <button class="btn btn-primary ml-auto">@lang('Save')</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
    
</div>
@stop

Modules/PagesWebsite/Resources/views/pagewebsites/index.blade.php


@extends('core::layouts.app')
@section('title', __('Pages Website'))
@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">@lang('Pages Website')</h1>
    <a href="{{ route('settings.pagewebsites.create') }}" class="btn btn-sm btn-success shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i> @lang('Create')</a>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="row mb-2">
          <div class="col-sm-12">
              <small>@lang('All the page links will be displayed in the footer menu of the website home page')</small>
          </div>
        </div>
        @if($data->count() > 0)
            <div class="card">
                <div class="table-responsive">
                    <table class="table card-table table-vcenter text-nowrap">
                        <thead class="thead-dark">
                            <tr>
                                <th>@lang('Title')</th>
                                <th>@lang('Active')</th>
                                <th>@lang('Date Created')</th>
                                <th>@lang('Date Modified')</th>
                                <th>@lang('Action')</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>
                                <td>

                                    <a href="{{ route('settings.pagewebsites.edit', $item->id) }}">{{ $item->title }}</a>
                                </td>
                                 <td>
                                    @if($item->is_active)
                                        <span class="badge badge-success">@lang('Active')</span>
                                    @else
                                        <span class="badge badge-warning">@lang('Not Active')</span>
                                    @endif
                                    
                                </td>
                               <td>
                               
                                <div class="small text-muted">
                                        {{$item->created_at->format('M j, Y')}}
                                </div>
                                </td>
                                <td>
                                        <div class="small text-muted">
                                                {{$item->updated_at->format('M j, Y')}}
                                        </div>
                                </td>
                                
                                <td>
                                     <div class="d-flex">
                                        <div class="p-1 ">
                                             <a href="{{ route('settings.pagewebsites.edit', $item->id) }}" class="btn btn-sm btn-primary">@lang('Edit')</a>
                                        </div>
                                        <div class="p-1 ">
                                                <form method="post" action="{{ route('settings.pagewebsites.destroy', $item->id) }}" onsubmit="return confirm('@lang('Confirm delete?')');">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-sm btn-danger btn-clean">
                                                        @lang('Delete')
                                                    </button>
                                                </form>
                                        </div>
                                    </div>
                                   
                                    
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        @endif
        <div class="mt-4">
            {{ $data->appends( Request::all() )->links() }}
        </div>
        
        @if($data->count() == 0)
        <div class="alert alert-primary text-center">
            <i class="fe fe-alert-triangle mr-2"></i> @lang('No page found')
        </div>
        @endif
    </div>
    
</div>

@stop