Modules/ModulesManager/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Authorized users
Route::middleware('auth')->group(function () {

    Route::middleware('can:admin')->prefix('settings')->name('settings.')->group(function () {
        // Upgrade
        Route::get('modulesmanager', 'ModulesManagerController@index')->name('modulesmanager.index');
        Route::get('migreatemodule/{type}', 'ModulesManagerController@migrateModule')->name('modulesmanager.migreatemodule');
        Route::post('modulesmanager/install', 'ModulesManagerController@install')->name('modulesmanager.install');
        Route::post('modulesmanager/update/{product_id}', 'ModulesManagerController@update')->name('modulesmanager.update');


    });

});

Modules/ModulesManager/Entities/PurchaseManager.php
<?php

namespace Modules\ModulesManager\Entities;

use Illuminate\Database\Eloquent\Model;

class PurchaseManager extends Model
{
    protected $dates = [
        'created_at',
        'updated_at',
    ];
  
    protected $fillable = [
        'product_id',
        'product_name',
        'purchase_code',
        'email_username_purchase',
        'path_main',
        'version',
        'verify_type',
        'created_at',
        'updated_at',
    ];
    
}

Modules/ModulesManager/Http/Controllers/ModulesManagerController.php
<?php

namespace Modules\ModulesManager\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use GuzzleHttp\Client as GuzzleClient;
use Modules\Core\Library\License;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Modules\ModulesManager\Entities\PurchaseManager;

class ModulesManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index(Request $request, License $license)
    {
        $products_purchased = PurchaseManager::all();
        $data = $license->getListProducts('oneresumecv');
        return view('modulesmanager::index', compact('data','products_purchased'));
    }

    public function migrateModule(Request $request, $type = "update")
    {
        // Migrate DB
        $message = __('Update module successfully');
        
        if ($type == "install") {
            $message = __('Install module succeszsfully');
        }
        
        try {

            Artisan::call('migrate', ["--force" => true]);
            Artisan::call('translation:sync-missing-translation-keys');
            Artisan::call('optimize:clear');


        } catch (\Exception $e) {

            return redirect()->back()
                ->with('error', 'Error: ' . $e->getMessage());
        }

        return redirect()->back()
                    ->with('success', $message);
       
    }

    public function install(Request $request)
    {

        $request->validate([
            'license'     => 'required|string',
            'product_id'  => 'required|string',
            'email_username_purchase'  => 'required|string',
            'product_name'  => 'required|string',
            'verify_type'  => 'required|string|in:envato,non_envato',
        ]);

        $license_code = trim($request->input('license'));
        $product_id = trim($request->input('product_id'));
        $email_username_purchase = trim($request->input('email_username_purchase'));
        $path_main = trim($request->input('path_main'));
        $verify_type = trim($request->input('verify_type'));
        $product_name = trim($request->input('product_name'));

        $item = PurchaseManager::where('product_id', $product_id)->first();
        // check exits purchase code
        if ($item) {
            return redirect()->back()
                    ->with('error', __('This modules or themes is already installed'));
        }

        $license = new License($product_id,$verify_type);

        // active license
        $response = $license->activateLicense($license_code, $email_username_purchase);
        if (!$response['status']) {

            return redirect()->back()
                    ->with('error', $response['message']);
        }


        $response = $license->downloadUgrade($license_code, $email_username_purchase, $path_main,true);
        if (!$response['status']) {
            // roll back
            $license->deactivateLicense($license_code, $email_username_purchase);
            return redirect()->back()
                    ->with('error', $response['message']);
        }
        // Active success add new record
        $item = PurchaseManager::create([
            "product_id" => $product_id,
            "product_name" => $product_name,
            "purchase_code" => $license_code,
            "verify_type" => $verify_type,
            "email_username_purchase" => $email_username_purchase,
            "path_main" => $path_main,
            "version" => '1.0.0'
        ]);

        try {
            
            Artisan::call('module:publish');
            // publish all language modules
            publishLangModule();

            $item->version = $response['version_new'];
            $item->save();

            return redirect()->route('settings.modulesmanager.migreatemodule', array('type' => 'install'));

        } catch (\Exception $e) {

            // revert deactive license
            $response = $license->deactivateLicense($item->purchase_code, $item->email_username_purchase);
            return redirect()->back()
                ->with('error', 'Error install: ' . $e->getMessage());

        }
        
    }

    public function update(Request $request, $product_id)
    {
        $item = PurchaseManager::where('product_id', $product_id)->first();
        if ($item) {
            // check exits purchase code
            $license = new License($item->product_id, $item->verify_type, $item->version);

            // verify license
            $response = $license->verifyLicense($item->purchase_code, $item->email_username_purchase);
            if (!$response['status']) {

                return redirect()->back()
                        ->with('error', $response['message']);
            }

            $response = $license->downloadUgrade($item->purchase_code, $item->email_username_purchase,$item->path_main,false);
            
            if (!$response['status']) {
                // roll back
                return redirect()->back()
                        ->with('error', $response['message']);
            }

            try {

                // Clear cache, routes, views
                Artisan::call('optimize:clear');
                Artisan::call('module:publish');
                
                // publish all language modules
                publishLangModule();

                $item->version = $response['version_new'];
                $item->save();

                return redirect()->route('settings.modulesmanager.migreatemodule', array('type' => 'update'));

            } catch (\Exception $e) {
                // revert deactive license
                $response = $license->deactivateLicense($item->purchase_code, $item->email_username_purchase);
                return redirect()->back()
                    ->with('error', 'Error install: ' . $e->getMessage());

            }

        }
        abort(404);
        
    }

}

Modules/ModulesManager/Resources/views/index.blade.php
@extends('core::layouts.app')
@section('title', __('Module managers'))
@section('content')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
	<h1 class="h3 mb-0 text-gray-800">@lang('Modules manager')</h1>
</div>
<div class="row">
	<div class="col-md-12">
		@if($data['products'] && count($data) > 0)
		<div class="row row_blog_responsive pt-4 clearfix">
			@foreach($data['products'] as $item)
			@php
				$check = check_product_purchase($item['pd_pid']);
				$product_version = get_latest_version_product_id($item['pd_pid']);
			@endphp
			<div class="col-xl-5 col-lg-6 col-md-4 col-sm-6 col-12 itembb">
				<div class="clearfix blog-bottom blog blogitemlarge">
					
					<div class="content_blog clearfixflex flex-column flex-lg-row">
						<p title="{{$item['pd_name']}}" class="min-h-100 p-2">
							{{$item['pd_details']}}
						</p>
						<div class="p-2">
							<h6 class="font-weight-bold text-secondary text-uppercase mb-1">{{ $item['pd_name'] }}</h6>
						</div>
						@if($check)
							@if($product_version && $product_version['latest_version'] != $check->version)
							<span class="p-2 text-warning">@lang('Version :version is available. Update now',['version' => $product_version['latest_version']])</span>
							@endif
							<div class="d-flex p-2">
								<button href="#" class="btn btn-sm btn-success mr-2" disabled><i class="fas fa-check-circle"></i> @lang('Installed')</button>	
								@if($product_version && $product_version['latest_version'] != $check->version)
									<form method="post" id="formUpdateVersion" action="{{ route('settings.modulesmanager.update', $item['pd_pid']) }}" >
				                      @csrf
				                      <button type="submit" id="btnUpdateVersion" class="btn btn-sm btn-danger">
				                      	<i class="fas fa-download"></i> @lang("Update") {{$product_version['latest_version']}}
				                      </button>
				                    </form>
								@else
									<button href="#" class="btn btn-sm btn-primary" disabled>@lang('Version'): {{$check->version}}</button>
								@endif
							</div>
						@else
							<div class="d-flex p-2">
								<a href="{{$item['pd_url_detail']}}" target="_blank" class="btn btn-sm btn-secondary mr-2"><i class="fas fa-eye"></i> @lang("Detail")</a>
								<a href="#" data-toggle="modal" data-productid="{{$item['pd_pid']}}" data-name="{{$item['pd_name']}}" data-pathmain="{{$item['pd_path_main_file']}}" 
								@if($item['envato_id'])
									 data-verifytype="envato" 
								@else
									 data-verifytype="non_envato" 
								@endif
								data-productname="{{$item['pd_name']}}" 
								data-target="#installModule" class="btninstallModule btn btn-sm btn-primary"><i class="fab fa-instalod"></i> @lang("Install now")</a>
							</div>
						@endif
					</div>
				</div>
			</div>
			@endforeach
		</div>
		@endif
	</div>
</div>
<div class="modal fade" id="installModule" tabindex="-1" role="dialog" aria-labelledby="installModuleLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title"><i class="fas fa-file-archive"></i> @lang('Install') <span id="installModuleTitle"></span> </h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form  action="{{route('settings.modulesmanager.install')}}" id="installModuleForm" method="post" enctype='multipart/form-data'>
				@csrf
				<div class="modal-body">
					<input type="text" class="form-control" hidden="" name="verify_type" required="" id="verify_type">
					<input type="text" class="form-control" hidden="" name="path_main" required="" id="path_main">
					<input type="text" class="form-control" hidden="" name="product_id" required="" id="product_id">
					<input type="text" class="form-control" hidden="" name="product_name" required="" id="product_name">
					<div class="form-group">
						<label for="name" class="col-form-label">@lang('Enter License'):</label>
						<input type="text" class="form-control" name="license" required="" id="license">
					</div>
					<div class="form-group">
						<label for="email" class="col-form-label">@lang('Email purchase'):</label>
						<input type="email" class="form-control" name="email_username_purchase" required="" id="email_username_purchase">
					</div>
					<div class="form-group">
						<label for="name" class="col-form-label">@lang('Notes'):</label>
						<div class="alert alert-primary">
							<ul class="mb-0">
								<li>@lang('Feature just can install modules or themes. Cannot use for reinstall main script')</li>
								<li>@lang("Make sure your server doesn't block the permissions to install")</li>
							</ul>
						</div>
					</div>
					
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">@lang('Close')</button>
					<button type="submit" id="btnInstallModuleModal" class="btn btn-primary">@lang('Install')</button>
				</div>
			</form>
		</div>
	</div>
</div>


@push('scripts')
      <script src="{{ Module::asset('modulesmanager:js/modulemanager.js') }}" ></script>
 @endpush
@stop

Modules/ModulesManager/Resources/views/moduletemplates/module-sidebar.blade.php
@can('admin')
<li class="nav-item {{ (request()->is('settings/modulesmanager*')) ? 'active' : '' }}">
	<a class="nav-link" href="{{ route('settings.modulesmanager.index') }}" >
		<i class="fas fa-box"></i>
		<span>@lang('Modules')</span>
	</a>
</li>
@endcan